name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0
  workflow_dispatch: # Allow manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run make:win

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer
        path: out/make/squirrel.windows/x64/*.exe

  create-release:
    needs: build-windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: windows-installer
        path: ./artifacts

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Tournament Brackets ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          ## Tournament Brackets ${{ github.ref_name }}
          
          ### Download
          - **Windows**: Download the `.exe` file below
          
          ### Features
          - Double elimination tournament brackets
          - Support for 4-512 players
          - Comprehensive rematch avoidance system
          - Cross-stream placement to prevent early rematches
          
          ### Installation
          1. Download the `.exe` file
          2. Run the installer
          3. Launch Tournament Brackets from your Start Menu
          
          ### Changes
          See the commit history for detailed changes in this release.

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/tournament-brackets-1.0.0 Setup.exe
        asset_name: TournamentBrackets-Setup-${{ github.ref_name }}.exe
        asset_content_type: application/octet-stream